= Demolishing the Silos of Naturalism
:last-update-label:

[quote, Encyclopedia Britannica, britannica.com/science/science]
science, any system of knowledge that is concerned with the physical world and its phenomena and that entails **unbiased** **observations** and **systematic experimentation**...


== Scientific principles established in the west

The assumption that the universe was logical, ordered and capable of being understood was born from the mind of Christianity in western civilization. 

Genesis 1:1
In the beginning God created the heavens and the earth.

This was not a God fashioned from within our universe but one that existed prior to its creation from nothing. A god that exists within our world must have had an even greater god outside of time and space to have existed and created them. 

[quote, First Book of Thessalonians, St. Paul]
1 Thessalonians 5  21 but **test everything**; hold fast what is good. 

[quote, 1 Corinthians 14:40]
But all things should be done decently and in **order**.

[quote, 1 Corinthians 14:33]
For God is not a God of __confusion__ but of **peace**.

== The goals of science

[quote, Book of Matthew, St. Matthew]
Matthew 7:7 “**Ask**, and it will be given to you; **seek**, and you will find; **knock**, and it will be opened to you.

[quote, Book of Proverbs, King Solomon]
Proverbs 25:2 “It is the glory of God to conceal a thing, but the honor of kings is to **search out a matter**.”


[quote, Jesus, John 14:6]
Jesus said to him, “I am the way, and the truth, and the life. No one comes to the Father except through me.

== The limitations of science




