= Demolishing the Silos of Naturalism
Last updated: January 15, 2023

[quote, Encyclopedia Britannica, britannica.com/science/science]
science, any system of knowledge that is concerned with the physical world and its phenomena and that entails **unbiased** **observations** and **systematic experimentation**...

[quote, 1 Thessalonians 5:21, St. Paul]
but **test everything**; hold fast what is good. 

[quote, 1 Corinthians 14:40]
But *all* things should be done decently and in **order**.

[quote, 1 Corinthians 14:33]
For God *is not* a God of __confusion__ but of **peace**.


== Scientific principles established in the west

The assumption that the universe was logical, ordered and capable of being understood was born in the mind of Christianity in western civilization. 

[quote, Genesis 1:1]
In the beginning God created the heavens and the earth.

This was not a god created from within our universe, This was not a god crafted from matter that required a nessessary cause. The God of the Jews, and Christianity is He who defines time, matter and space. He is truth. God does not discover anything new. He defines truth and we discover that truth.  We discover and learn new things,  **Johannes Kepler** perhaps phrased this best, _"I was merely thinking God's thoughts after him."_ 

[quote, Proverbs 25:2, King Solomon]
“It is the glory of God to conceal a thing, but the honor of kings is to **search out a matter**.”



== The goals of science

[quote, Matthew 7:7, St. Matthew]
“**Ask**, and it will be given to you; **seek**, and you will find; **knock**, and it will be opened to you.




[quote, Jesus, John 14:6]
Jesus said to him, “I am the way, and the truth, and the life. No one comes to the Father except through me.

== The limitations of science




